-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 10:45:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answers` (
  `idanswers` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idanswers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questions` (
  `idquestions` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `answers_idanswers` INT NOT NULL,
  PRIMARY KEY (`idquestions`, `answers_idanswers`),
  CONSTRAINT `fk_questions_answers`
    FOREIGN KEY (`answers_idanswers`)
    REFERENCES `mydb`.`answers` (`idanswers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`score` (
  `idscore` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `answers_idanswers` INT NOT NULL,
  PRIMARY KEY (`idscore`, `answers_idanswers`),
  CONSTRAINT `fk_score_answers1`
    FOREIGN KEY (`answers_idanswers`)
    REFERENCES `mydb`.`answers` (`idanswers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `idstudents` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `questions_idquestions` INT NOT NULL,
  `questions_answers_idanswers` INT NOT NULL,
  PRIMARY KEY (`idstudents`, `questions_idquestions`, `questions_answers_idanswers`),
  CONSTRAINT `fk_students_questions1`
    FOREIGN KEY (`questions_idquestions` , `questions_answers_idanswers`)
    REFERENCES `mydb`.`questions` (`idquestions` , `answers_idanswers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students_has_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students_has_score` (
  `students_idstudents` INT NOT NULL,
  `students_questions_idquestions` INT NOT NULL,
  `students_questions_answers_idanswers` INT NOT NULL,
  `score_idscore` INT NOT NULL,
  PRIMARY KEY (`students_idstudents`, `students_questions_idquestions`, `students_questions_answers_idanswers`, `score_idscore`),
  CONSTRAINT `fk_students_has_score_students1`
    FOREIGN KEY (`students_idstudents` , `students_questions_idquestions` , `students_questions_answers_idanswers`)
    REFERENCES `mydb`.`students` (`idstudents` , `questions_idquestions` , `questions_answers_idanswers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_score_score1`
    FOREIGN KEY (`score_idscore`)
    REFERENCES `mydb`.`score` (`idscore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
